version: '3'

services:
  shopper_db:
    container_name: shopper_db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - shopper_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  shopper_api:
    container_name: shopper_api
    build: .
    restart: unless-stopped
    depends_on:
      - shopper_db
    volumes:
      - .:/app
      - static:/static
      - media:/media
    env_file:
      - .env
    command: ["python", "/app/shopper/manage.py", "runserver", "0:80"]
    ports:
      - "8000:80"

volumes:
  static:
  media:
  shopper_db: